const s = {
    error_loading: "Error Loading",
    nothing_to_show: "Nothing to show yet",
    loading: "Loading ...",
    report: "Report",
    auto_refresh: "Auto-refresh",
    color_blind_mode: "Color blind mode",
    participants: "Participants",
    comments: "Comments",
    votes: "Votes",
    opinion_groups: "Opinion Groups",
    toggle_model: "Toggle Model",
    current_model: "Current Model:",
    loading_consensus: "...Loading Consensus",
    loading_groups: "...Loading Groups",
    loading_uncertainty: "...Loading Uncertainty",

    // Overview
    overview_title: "Overview",
    overview_description: "Pol.is is a real-time survey system that helps identify the different ways a large group of people think about a divisive or complicated topic. Here's a basic breakdown of some terms you'll need to know in order to understand this report.",
    participants_label: "Participants:",
    participants_desc: "These are the people who participated in the conversation by voting and writing statements. Based on how they voted, each participant is sorted into an opinion group.",
    statements_label: "Statements:",
    statements_desc: "Participants may submit statements for other participants to vote on. Statements are assigned a number in the order they're submitted.",
    opinion_groups_label: "Opinion groups:",
    opinion_groups_desc: "Groups are made of participants who voted similarly to each other, and differently from the other groups.",
    conversation_run_by: "This pol.is conversation was run by ",
    topic_was: "The topic was '",

    // Numbers
    people_voted: "people voted",
    people_grouped: "people grouped",
    votes_cast: "votes were cast",
    statements_submitted: "statements were submitted",
    votes_per_voter: "votes per voter on average",
    statements_per_author: "statements per author on average",

    // Narrative Report
    narrative_report_beta: "Narrative Report — Beta Version",
    narrative_report_title: "Pol.is' New Narrative Report",
    narrative_report_beta_desc: "You're seeing a beta version of Polis' new narrative report—generated with the help of Large Language Models (LLMs). We are currently crowdsourcing evaluations of this report with the help of our user community—people like you! Thank you for participating in these early evaluations.",
    narrative_report_bottleneck_desc: "This report has been designed to address a critical bottleneck in Polis conversations: human facilitators spend countless hours turning Polis results into accessible reports for both participants and decision-makers. Our first goal is to substantially augment human report writing, getting any user most of the way to an acceptable deliverable report in a fraction of the time it would a professional data scientist manually.",
    narrative_report_llm_warning: "Large language models can make big mistakes. Detailed human review is absolutely critical, even if almost all clauses are accurate. We aim to improve both quality and speed through ongoing iteration.",
    narrative_report_generating_title: "Generating a Polis Narrative Report",
    narrative_report_generating_desc: "You can currently choose between Gemini and Claude, with many more options coming soon. You can use the same link to access the report throughout the conversation. A new intermediary report is recomputed every hour, and a final report will be generated once the conversation is closed. To keep a record of intermediary reports, please save them as PDFs using print to PDF.",
    narrative_report_sharing_warning: "We advise against sharing intermediary narrative reports with the broader public, as it can change significantly throughout the conversation and may contain errors. Once the conversation is complete, you can review the final report and share it as is or create a custom version for wider distribution.",
    narrative_report_reviewing_title: "Reviewing the Final Narrative Report",
    narrative_report_reviewing_desc: "The report will very likely contain errors. Each clause in the report should be accompanied by citations, drawn from statements submitted by participants. Please review each clause against the cited statements and flag the following:",
    narrative_report_reviewing_list_1: "Clauses that misrepresent the cited statements",
    narrative_report_reviewing_list_2: "Statistical or numeric issues with the summary",
    narrative_report_reviewing_list_3: "Redundant clauses that are not helpful",
    narrative_report_reviewing_list_4: "Clauses that do not have accompanying citations",
    narrative_report_feedback_desc: "For quality control purposes, you will not be able to add new clauses to the Polis narrative report. We welcome your feedback on the report, and will use it to improve the report generation process.",

    // Collective Statements
    collective_statement_title: "Candidate Collective Statement",
    collective_generated: "Generated",
    collective_at: "at",
    collective_statement_label: "Statement",
    collective_cited_comments: "Cited Comments",
    collective_no_comments: "No comments cited",
    collective_loading: "Loading collective statements...",
    collective_none: "No collective statements have been generated yet.",
    collective_count_statements: "statements",
    collective_of: "of",
    collective_statement_modal_trends: "Based on voting trends thus far",
    collective_statement_modal_generating: "Generating candidate collective statement...",
    collective_statement_modal_wait: "This may take a moment as we analyze voting patterns and comments.",
    collective_statement_modal_note: "Note:",
    collective_statement_modal_note_desc: "This candidate collective statement was generated using AI based on the voting patterns and comments from all participants. It represents areas of shared understanding and consensus on this topic.",

    // Comments Report & Delphi
    comments_report_run_delphi_confirm: "Are you sure you want to run a new Delphi analysis? This will erase previous results, and may take several minutes.",
    comments_report_cancel: "Cancel",
    comments_report_run_analysis: "Run Analysis",
    comments_report_discover_delphi: "Discover more with Delphi - advanced data analysis and AI - Upgrade at ",
    comments_report_close: "Close",
    comments_report_no_table: "DynamoDB connected but the required table doesn't exist yet. This is normal until the Delphi pipeline has been run for this conversation.",
    comments_report_no_data: "No LLM topic data available yet",
    comments_report_fail_retrieve: "Failed to retrieve LLM topics",
    comments_report_fail_connect: "Failed to connect to the Delphi endpoint",
    comments_report_loading_viz: "Loading visualizations...",
    comments_report_run_new: "Run New Delphi Analysis",
    comments_report_no_viz: "No visualizations available yet. Click \"Run New Delphi Analysis\" to create a new job.",
    comments_report_interactive_viz: "Interactive Topics Visualization (all comments)",
    comments_report_created: "Created:",
    comments_report_interactive_layer_viz: "Interactive Visualization",
    comments_report_static_layer_viz: "Static Visualization",
    comments_report_no_viz_job: "No visualizations available for this job yet.",
    comments_report_viz_wait: "Visualizations may take a few minutes to generate. You can refresh the page to check for updates.",
    comments_report_loading_topic_narrative: "Loading topic and narrative data...",
    comments_report_no_topic_narrative: "No topic or narrative data available yet. Run a Delphi analysis to generate topics and narratives.",
    comments_report_showing_job: "Showing reports for Job ID:",
    comments_report_select_section: "Select a report section...",
    comments_report_topics_identified: "topics identified",
    comments_report_narratives_generated: "narratives generated",
    comments_report_topic_status: "Topic Status:",
    comments_report_narrative_status: "Narrative Status:",
    comments_report_topic_identified: "Identified",
    comments_report_topic_not_available: "Not Available",
    comments_report_narrative_generated: "Generated",
    comments_report_narrative_pending: "Pending",
    comments_report_topic_info: "Topic Info:",
    comments_report_not_enough_data: "Not enough data has been provided for analysis, please check back later",
    comments_report_json_error: "Report data is not in the expected JSON format.",

    // Topic Report
    topic_report_no_data: "No report data found for this topic",
    topic_report_no_narrative: "No narrative report available for this topic",
    topic_report_generate_hint: "To generate narrative reports, use the \"Generate Narrative Report\" button in the ",
    topic_report_comments_report_link: "Comments Report page.",
    topic_report_referenced_comments: "Comments Referenced in This Topic",
    topic_report_narrative_summaries: "Narrative Summaries",
    topic_report_loading: "Loading topic report...",

    // Topic Data Provider
    topic_data_loading: "Loading topics...",
    topic_data_error: "Error loading data: {error}",

    // Topic Sections Builder
    topic_sections_divisive_global: "Divisive Comments (Global)",
    topic_sections_consensus_global: "Cross-Group Consensus (Global)",
    topic_sections_uncertainty_global: "High Uncertainty Comments (Global)",
    topic_sections_no_runs: "No topic runs found",

    // Topic Selector
    topic_selector_global_analysis: "Global Analysis",
    topic_selector_layer_topics: "Layer {layer} Topics",

    // Topic Stats
    topic_stats_fail_load: "Failed to load topic statistics",
    topic_stats_loading: "Loading topic statistics...",
    topic_stats_title: "Topic Statistics",
    topic_stats_no_data: "No data available. To generate, run a delphi analysis on the ",

    // Topic Tables
    topic_tables_threshold_min_comments: "Candidate collective statements require at least {min} comments with ",
    topic_tables_threshold_consensus: "≥{val}% consensus and ",
    topic_tables_threshold_participation: "≥{val}% participation from every group",
    topic_tables_layer_fine: "Finer Grained",
    topic_tables_layer_fine_desc: "(Specific insights)",
    topic_tables_layer_coarse: "Coarse",
    topic_tables_layer_coarse_desc: "(Big picture themes)",
    topic_tables_layer_medium: "Medium",
    topic_tables_layer_medium_desc: "(Balanced overview)",
    topic_tables_count_topics: "{count} Topics",
    topic_tables_boxplots: "Boxplots",
    topic_tables_col_topic: "Topic",
    topic_tables_col_comments: "Comments",
    topic_tables_col_total_votes: "Total Votes",
    topic_tables_col_avg_votes: "Avg Votes/Comment",
    topic_tables_col_group_consensus: "Group Consensus",
    topic_tables_col_action: "Action",
    topic_tables_btn_collective: "Collective Statement",
    topic_tables_btn_votes: "Votes",
    topic_tables_btn_beeswarm: "Beeswarm",

    // Beeswarm Modal
    beeswarm_modal_title: "Group-Aware Consensus Distribution",
    beeswarm_modal_desc: "Each circle represents a comment. Position shows how similarly groups voted. Hover to see the group vote breakdown.",

    // All Comments Modal
    all_comments_modal_analysis: " - Comments Analysis",
    all_comments_modal_title: "Comments: Group-Aware Consensus vs. Votes",
    all_comments_modal_desc: "Each dot represents a comment. Hover for details.",
    all_comments_modal_no_comments: "No comments to display",

    // Layer Distribution Modal
    layer_distribution_modal_consensus: " - Consensus Distribution",
    layer_distribution_modal_desc: "Box plots showing the distribution of group-aware consensus values for comments with at least 5 votes within each topic. The box shows the quartiles, the line inside is the median, and outliers are shown as individual points. Comments with fewer than 5 votes are excluded as they default to 0.333 consensus.",
    layer_distribution_modal_y_axis: "Group-Aware Consensus",
    layer_distribution_modal_x_axis: "Topics",

    // Topic Overview Scatterplot
    topic_overview_scatterplot_title: "Topic Overview: Group-Aware Consensus",
    topic_overview_scatterplot_y_axis_label: "Y-axis (Group-Aware Consensus):",
    topic_overview_scatterplot_y_axis_desc: "Measures agreement across different participant groups from PCA2. Higher values indicate topics where groups tend to vote similarly (cross-group agreement).",
    topic_overview_scatterplot_x_axis_label: "X-axis:",
    topic_overview_scatterplot_x_axis_desc: "Average votes per comment",
    topic_overview_scatterplot_bubble_label: "Bubble size:",
    topic_overview_scatterplot_bubble_desc: "Number of comments",
    topic_overview_scatterplot_colors_label: "Colors:",
    topic_overview_scatterplot_green: "Green",
    topic_overview_scatterplot_high_consensus: " = high group consensus, ",
    topic_overview_scatterplot_red: "Red",
    topic_overview_scatterplot_low_consensus: " = low group consensus",

    // Topic Page
    topic_page_loading: "Loading topic data...",
    topic_page_not_found: "Topic not found",
    topic_page_go_back: "Go Back",
    topic_page_back_to_topics: "← Back to Topics",
    topic_page_total_agree_votes: "Total Agree Votes",
    topic_page_total_disagree_votes: "Total Disagree Votes",
    topic_page_votes_count: "{count} votes",
    topic_page_divisiveness_title: "Comment Divisiveness Distribution",
    topic_page_divisiveness_desc: "Each circle represents a comment. Position shows how similarly groups voted. Hover to see the group vote breakdown.",
    topic_page_insufficient_consensus: "Insufficient consensus:",
    topic_page_insufficient_consensus_desc: "Candidate collective statements require topics with strong cross-group agreement to ensure meaningful representation.",
    topic_page_comments_referenced: "Comments Referenced",
    topic_page_narrative_err_refresh: "Unable to generate candidate collective statement. Please try refreshing the page.",
    topic_page_narrative_summary: "Narrative Summary",
    topic_page_consensus_vs_engagement: "Consensus vs Engagement",
    topic_page_consensus_vs_engagement_desc: "This visualization shows how group consensus relates to voting engagement for each comment. Comments with high consensus and high engagement represent areas of strong agreement or disagreement across the conversation.",
    topic_page_all_comments_n: "All Comments ({count})",
    topic_page_all_comments_this_topic: "All comments in this topic.",

    // Comment List
    comment_list_missing_votes: "Missing vote counts",
    comment_list_no_votes: "No votes yet",
    comment_list_agreed: " Agreed\n",
    comment_list_disagreed: " Disagreed\n",
    comment_list_passed: " Passed\n",
    comment_list_respondents: " Respondents",
    comment_list_group_label: "Group {key}",
    comment_list_overall: "Overall",
    comment_list_statement: "Statement",

    // Raw Data Export
    export_title: "Raw Data Export (Anonymous)",
    export_description: "The following data exports are anonymized. Participants are identifed by an integer representing the order in which they first voted. For a full description of files and columns, please see: ",
    export_summary: "Summary: ",
    export_comments: "Comments: ",
    export_may_take_minutes: " (may take up to several minutes)",
    export_votes_history: "Votes history: ",
    export_as_event_log: " (as event log)",
    export_votes_matrix: "Votes matrix: ",
    export_as_matrix: " (as comments x participants matrix)",
    export_importance_matrix: "Importance matrix: ",
    export_comment_groups: "Comment groups: ",
    export_public_api: "Public API endpoints (read only, Jupyter notebook friendly)",
    export_attribution_title: "Attribution of Polis Data",
    export_attribution_license: "All Polis data is licensed under a Creative Commons Attribution 4.0 International license: ",
    export_statement_begin: "--------------- BEGIN STATEMENT ---------------",
    export_statement_end: "--------------- END STATEMENT ---------------",
    export_attribution_description: "Data was gathered using the Polis software (see: compdemocracy.org/polis and github.com/compdemocracy/polis) and is sub-licensed under CC BY 4.0 with Attribution to The Computational Democracy Project. The data and more information about how the data was collected can be found at the following link: ",
    export_attribution_best_practices: "For further information on best practices for Attribution of CC 4.0 licensed content Please see:",

    // Topics Viz Report
    topics_viz_report_loading: "Loading visualizations...",
    topics_viz_report_granularity: "Topic Granularity",
    topics_viz_report_desc: "Each colored region represents a topic—comments that share similar themes, language, or subject matter. Polis 2 uses advanced NLP embeddings and hierarchical clustering to mathematically identify these topics. Choose your preferred level of detail: finer grained shows specific subtopics, while coarse shows broader themes.",
    topics_viz_report_count_topics: "{count} Topic{count, plural, one {} other {s}}",
    topics_viz_report_interactive_title: "Layer {layer} Interactive Visualization",
    topics_viz_report_static_title: "Layer {layer} Static Visualization",
    topics_viz_report_vis_title: "Layer {layer} visualization",
    topics_viz_report_no_vis: "No visualizations available for this job yet.",
    topics_viz_report_vis_wait: "Visualizations may take a few minutes to generate.",
    topics_viz_report_no_jobs: "No visualization jobs found.",

    // Headers & Overview placeholders
    majority_opinion: "Majority Opinion",
    uncertainty: "Uncertainty",
    all_comments: "All Comments",
    participant_groups: "Participant Groups",
}

export default s
