const s = {
    error_loading: "読み込みエラー",
    nothing_to_show: "表示するデータがまだありません",
    loading: "読み込み中...",
    report: "資料・レポート",
    auto_refresh: "自動更新",
    color_blind_mode: "カラーユニバーサルデザイン（色覚サポート）",
    participants: "参加者",
    comments: "意見数",
    votes: "投票数",
    opinion_groups: "意見グループ",
    toggle_model: "モデル切り替え",
    current_model: "現在のモデル:",
    loading_consensus: "...コンセンサスを読み込み中",
    loading_groups: "...グループを読み込み中",
    loading_uncertainty: "...不確実性を読み込み中",

    // Overview
    overview_title: "概要",
    overview_description: "Pol.is（ポリス）は、大規模なグループが、分裂しがちなトピックや複雑なトピックについてどのように考えているかを特定する、リアルタイムの調査システムです。このレポートを理解するために必要な用語の基本的な内訳は以下の通りです。",
    participants_label: "参加者:",
    participants_desc: "投票や意見の執筆によって会話に参加した人々です。投票内容に基づいて、各参加者は「意見グループ」に分類されます。",
    statements_label: "意見（ステートメント）:",
    statements_desc: "参加者は、他の参加者が投票するための意見を提出することができます。提出された順に番号が割り当てられます。",
    opinion_groups_label: "意見グループ:",
    opinion_groups_desc: "お互いに似たような投票を行い、他のグループとは異なる投票を行った参加者で構成されるグループです。",
    conversation_run_by: "このPol.isの会話は、以下によって運営されました：",
    topic_was: "トピックは「",

    // Numbers
    people_voted: "人が投票",
    people_grouped: "人がグループ化",
    votes_cast: "票が投じられました",
    statements_submitted: "件の意見が送信されました",
    votes_per_voter: "1人あたりの平均投票数",
    statements_per_author: "1人あたりの平均送信意見数",

    // Narrative Report
    narrative_report_beta: "ナラティブ・レポート（ベータ版）",
    narrative_report_title: "新しいナラティブ・レポートについて",
    narrative_report_beta_desc: "現在表示されているのは、大規模言語モデル（LLM）の助けを借りて生成された、Polisの新しいナラティブ・レポートのベータ版です。私たちは現在、ユーザーコミュニティの皆様の協力（クラウドソーシング）を得て、このレポートの評価を行っています。初期評価へのご協力、ありがとうございます。",
    narrative_report_bottleneck_desc: "このレポートは、Polisの会話における重大なボトルネックを解消するために設計されました。これまでは、ファシリテーターがPolisの結果を参加者や意思決定者にとって分かりやすいレポートにまとめるために、膨大な時間を費やしてきました。私たちの第一の目標は、レポート作成作業を大幅に拡張し、専門のデータサイエンティストが手作業で行うよりもはるかに短い時間で、誰もが納得できるレベルのレポートを作成できるようにすることです。",
    narrative_report_llm_warning: "大規模言語モデルは大きな間違いを犯すことがあります。ほとんどの項目が正確であったとしても、人間による詳細な確認が極めて重要です。継続的な改善を通じて、品質とスピードの両方を向上させることを目指しています。",
    narrative_report_generating_title: "ナラティブ・レポートの生成について",
    narrative_report_generating_desc: "現在はGeminiとClaudeを選択できます（今後さらに多くのオプションが追加される予定です）。会話中、同じリンクからレポートにアクセスできます。中間レポートは1時間ごとに再計算され、会話が終了すると最終レポートが生成されます。中間レポートの記録を残すには、PDFとして保存（PDF印刷）してください。",
    narrative_report_sharing_warning: "中間レポートは会話の進行に伴い内容が大きく変わる可能性があり、誤りを含む場合もあるため、広く一般に公開することは避けてください。会話が終了したら、最終レポートを確認し、そのまま共有するか、配布用にカスタマイズしたバージョンを作成してください。",
    narrative_report_reviewing_title: "最終ナラティブ・レポートの確認",
    narrative_report_reviewing_desc: "レポートには誤りが含まれる可能性が非常に高いです。レポートの各項目には、参加者から提出された意見に基づく「引用」が添えられています。各項目を引用された意見と照らし合わせ、以下の点を確認・指摘してください：",
    narrative_report_reviewing_list_1: "引用された意見を誤解・誤認している項目",
    narrative_report_reviewing_list_2: "統計的または数値的な要約の誤り",
    narrative_report_reviewing_list_3: "役に立たない重複した項目",
    narrative_report_reviewing_list_4: "引用元のない項目",
    narrative_report_feedback_desc: "品質管理のため、ナラティブ・レポートに新しい項目をご自身で追加することはできません。レポートに関するフィードバックを歓迎します。いただいた意見はレポート生成プロセスの改善に役立てられます。",

    // Collective Statements
    collective_statement_title: "候補となる統合ステートメント",
    collective_generated: "生成日時：",
    collective_at: " ",
    collective_statement_label: "ステートメント",
    collective_cited_comments: "引用された意見",
    collective_no_comments: "引用された意見はありません",
    collective_loading: "統合ステートメントを読み込み中...",
    collective_none: "統合ステートメントはまだ生成されていません。",
    collective_count_statements: "件のステートメント",
    collective_of: "/",
    collective_statement_modal_trends: "これまでの投票傾向に基づく",
    collective_statement_modal_generating: "候補となる統合ステートメントを生成中...",
    collective_statement_modal_wait: "投票パターンと意見を分析しているため、しばらく時間がかかる場合があります。",
    collective_statement_modal_note: "注記：",
    collective_statement_modal_note_desc: "この候補となる統合ステートメントは、全参加者の投票パターンと意見に基づきAIによって生成されました。これは、このトピックに関する共通の理解と合意の領域を表しています。",

    // Comments Report & Delphi
    comments_report_run_delphi_confirm: "新しいDelphi分析を実行してよろしいですか？これまでの結果は消去され、完了までに数分かかる場合があります。",
    comments_report_cancel: "キャンセル",
    comments_report_run_analysis: "分析を実行",
    comments_report_discover_delphi: "Delphiでより多くの発見を - 高度なデータ分析とAI - 新しい分析を実行するには、pro.pol.isでアップグレードしてください： ",
    comments_report_close: "閉じる",
    comments_report_no_table: "DynamoDBには接続されましたが、必要なテーブルがまだ存在しません。これは、この会話に対してDelphiパイプラインが実行されるまでは正常な状態です。",
    comments_report_no_data: "LLMトピックデータはまだありません",
    comments_report_fail_retrieve: "LLMトピックの取得に失敗しました",
    comments_report_fail_connect: "Delphiエンドポイントへの接続に失敗しました",
    comments_report_loading_viz: "視覚化データを読み込み中...",
    comments_report_run_new: "新しいDelphi分析を実行",
    comments_report_no_viz: "表示できる視覚化データがまだありません。「新しいDelphi分析を実行」をクリックして、新しいジョブを作成してください。",
    comments_report_interactive_viz: "インタラクティブなトピック可視化（全意見）",
    comments_report_created: "作成日時：",
    comments_report_interactive_layer_viz: "インタラクティブ可視化",
    comments_report_static_layer_viz: "静的な可視化",
    comments_report_no_viz_job: "このジョブで使用できる視覚化データはまだありません。",
    comments_report_viz_wait: "視覚化データの生成には数分かかる場合があります。ページを更新して状況を確認してください。",
    comments_report_loading_topic_narrative: "トピックとナラティブデータを読み込み中...",
    comments_report_no_topic_narrative: "トピックまたはナラティブデータがまだありません。Delphi分析を実行してトピックとナラティブを生成してください。",
    comments_report_showing_job: "ジョブIDのレポートを表示中：",
    comments_report_select_section: "レポートセクションを選択...",
    comments_report_topics_identified: "件のトピックを特定",
    comments_report_narratives_generated: "件のナラティブを生成",
    comments_report_topic_status: "トピックの状態：",
    comments_report_narrative_status: "ナラティブの状態：",
    comments_report_topic_identified: "特定済み",
    comments_report_topic_not_available: "利用不可",
    comments_report_narrative_generated: "生成済み",
    comments_report_narrative_pending: "保留中",
    comments_report_topic_info: "トピック情報：",
    comments_report_not_enough_data: "分析に十分なデータが提供されていません。後でもう一度確認してください。",
    comments_report_json_error: "レポートデータが期待されるJSON形式ではありません。",

    // Topic Report
    topic_report_no_data: "このトピックのレポートデータが見つかりません",
    topic_report_no_narrative: "このトピックに使用できるナラティブ・レポートはありません",
    topic_report_generate_hint: "ナラティブ・レポートを生成するには、以下のページの「ナラティブ・レポートを生成」ボタンを使用してください：",
    topic_report_comments_report_link: "意見レポートのページ",
    topic_report_referenced_comments: "このトピックで参照されている意見",
    topic_report_narrative_summaries: "ナラティブ要約",
    topic_report_loading: "トピックレポートを読み込み中...",

    // Topic Data Provider
    topic_data_loading: "トピックを読み込み中...",
    topic_data_error: "データの読み込みエラー: {error}",

    // Topic Sections Builder
    topic_sections_divisive_global: "対立する意見（全体）",
    topic_sections_consensus_global: "グループを超えた共通認識（全体）",
    topic_sections_uncertainty_global: "不確実性の高い意見（全体）",
    topic_sections_no_runs: "トピックの実行結果が見つかりません",

    // Topic Selector
    topic_selector_global_analysis: "全体分析",
    topic_selector_layer_topics: "レイヤー {layer} のトピック",

    // Topic Stats
    topic_stats_fail_load: "トピック統計の読み込みに失敗しました",
    topic_stats_loading: "トピック統計を読み込み中...",
    topic_stats_title: "トピック統計",
    topic_stats_no_data: "データがありません。生成するには、以下のページで分析を実行してください：",

    // Topic Tables
    topic_tables_threshold_min_comments: "候補となる統合ステートメントには、少なくとも {min} 件の意見と、",
    topic_tables_threshold_consensus: "≥{val}% の共通認識、および",
    topic_tables_threshold_participation: "すべてのグループからの ≥{val}% の参加が必要です",
    topic_tables_layer_fine: "詳細",
    topic_tables_layer_fine_desc: "(具体的なインサイト)",
    topic_tables_layer_coarse: "大まか",
    topic_tables_layer_coarse_desc: "(全体的なテーマ)",
    topic_tables_layer_medium: "標準",
    topic_tables_layer_medium_desc: "(バランスの取れた概要)",
    topic_tables_count_topics: "{count} 件のトピック",
    topic_tables_boxplots: "ボックスプロット",
    topic_tables_col_topic: "トピック",
    topic_tables_col_comments: "意見数",
    topic_tables_col_total_votes: "総投票数",
    topic_tables_col_avg_votes: "意見あたりの平均投票数",
    topic_tables_col_group_consensus: "グループ共通認識",
    topic_tables_col_action: "アクション",
    topic_tables_btn_collective: "統合ステートメント",
    topic_tables_btn_votes: "投票",
    topic_tables_btn_beeswarm: "ビースウォーム",

    // Beeswarm Modal
    beeswarm_modal_title: "グループを考慮した共通認識の分布",
    beeswarm_modal_desc: "各円は意見を表しています。位置は、各グループがどれほど似た投票をしたかを示しています。ホバーするとグループごとの投票の内訳が表示されます。",

    // All Comments Modal
    all_comments_modal_analysis: " - 意見の分析",
    all_comments_modal_title: "意見：グループを考慮した共通認識 vs 投票数",
    all_comments_modal_desc: "各ドットは意見を表しています。ホバーすると詳細が表示されます。",
    all_comments_modal_no_comments: "表示する意見はありません",

    // Layer Distribution Modal
    layer_distribution_modal_consensus: " - 共通認識の分布",
    layer_distribution_modal_desc: "各トピック内で、少なくとも5票の投票があった意見のグループを考慮した共通認識の値の分布を示すボックスプロットです。ボックスは四分位数を示し、中の線は中央値、外れ値は個別の点として表示されます。5票未満の意見は、共通認識の初期値が0.333となるため除外されています。",
    layer_distribution_modal_y_axis: "グループを考慮した共通認識",
    layer_distribution_modal_x_axis: "トピック",

    // Topic Overview Scatterplot
    topic_overview_scatterplot_title: "トピックの概要：グループを考慮した共通認識",
    topic_overview_scatterplot_y_axis_label: "Y軸 (グループを考慮した共通認識):",
    topic_overview_scatterplot_y_axis_desc: "PCA2による異なる参加者グループ間での合意を測定します。値が高いほど、各グループが似た投票をする傾向（グループを超えた合意）があることを示します。",
    topic_overview_scatterplot_x_axis_label: "X軸:",
    topic_overview_scatterplot_x_axis_desc: "意見あたりの平均投票数",
    topic_overview_scatterplot_bubble_label: "バブルの大きさ:",
    topic_overview_scatterplot_bubble_desc: "意見数",
    topic_overview_scatterplot_colors_label: "色:",
    topic_overview_scatterplot_green: "緑",
    topic_overview_scatterplot_high_consensus: " = 高いグループ共通認識、",
    topic_overview_scatterplot_red: "赤",
    topic_overview_scatterplot_low_consensus: " = 低いグループ共通認識",

    // Topic Page
    topic_page_loading: "トピックデータを読み込み中...",
    topic_page_not_found: "トピックが見つかりません",
    topic_page_go_back: "戻る",
    topic_page_back_to_topics: "← トピック一覧に戻る",
    topic_page_total_agree_votes: "総同意数",
    topic_page_total_disagree_votes: "総不同意数",
    topic_page_votes_count: "{count} 票",
    topic_page_divisiveness_title: "意見の対立の分布",
    topic_page_divisiveness_desc: "各円は意見を表しています。位置は、各グループがどれほど似た投票をしたかを示しています。ホバーするとグループごとの投票の内訳が表示されます。",
    topic_page_insufficient_consensus: "合意が不十分です：",
    topic_page_insufficient_consensus_desc: "候補となる統合ステートメントには、有意義な代表性を確保するために、グループ間で強い共通認識があるトピックが必要です。",
    topic_page_comments_referenced: "参照された意見",
    topic_page_narrative_err_refresh: "候補となる統合ステートメントを生成できません。ページを更新してください。",
    topic_page_narrative_summary: "ナラティブ要約",
    topic_page_consensus_vs_engagement: "共通認識 vs 関与度",
    topic_page_consensus_vs_engagement_desc: "この視覚化は、各意見についてグループ間の共通認識が投票の関与度とどのように関連しているかを示しています。共通認識と関与度の両方が高い意見は、会話全体において強い賛成または反対がある領域を表しています。",
    topic_page_all_comments_n: "すべての意見 ({count})",
    topic_page_all_comments_this_topic: "このトピックに含まれるすべての意見。",

    // Comment List
    comment_list_missing_votes: "投票数が不足しています",
    comment_list_no_votes: "まだ投票がありません",
    comment_list_agreed: " 同意\n",
    comment_list_disagreed: " 不同意\n",
    comment_list_passed: " パス\n",
    comment_list_respondents: " 人の回答者",
    comment_list_group_label: "グループ {key}",
    comment_list_overall: "全体",
    comment_list_statement: "ステートメント",

    // Raw Data Export
    export_title: "生データの書き出し（アノニマス）",
    export_description: "以下のデータ書き出しは匿名化されています。参加者は、最初に投票した順序を表す整数によって識別されます。ファイルと列の詳細な説明については、以下を参照してください： ",
    export_summary: "集計内容： ",
    export_comments: "意見一覧： ",
    export_may_take_minutes: " （数分かかる場合があります）",
    export_votes_history: "投票履歴： ",
    export_as_event_log: " （イベントログとして）",
    export_votes_matrix: "投票行列： ",
    export_as_matrix: " （意見 x 参加者行列として）",
    export_importance_matrix: "重要度行列： ",
    export_comment_groups: "意見グループ： ",
    export_public_api: "パブリックAPIエンドポイント（読み取り専用、Jupyter Notebook対応）",
    export_attribution_title: "Polisデータの帰属（アトリビューション）",
    export_attribution_license: "すべてのPolisデータは、クリエイティブ・コモンズ 表示 4.0 国際 ライセンスの下で提供されています： ",
    export_statement_begin: "--------------- ステートメント開始 ---------------",
    export_statement_end: "--------------- ステートメント終了 ---------------",
    export_attribution_description: "データはPolisソフトウェア（参照：compdemocracy.org/polis および github.com/compdemocracy/polis）を使用して収集され、The Computational Democracy Projectへの帰属を条件にCC BY 4.0でサブライセンスされています。データおよび収集方法に関する詳細は、次のリンクで確認できます：",
    export_attribution_best_practices: "CC 4.0ライセンスのコンテンツの帰属に関するベストプラクティスの詳細は、以下を参照してください：",

    // Topics Viz Report
    topics_viz_report_loading: "可視化データを読み込み中...",
    topics_viz_report_granularity: "トピックの粒度",
    topics_viz_report_desc: "色分けされた各領域はトピック（似たテーマ、言語、または主題を共有する意見）を表しています。Polis 2は、高度なNLPエンベディングと階層的クラスタリングを使用して、これらのトピックを数学的に特定します。お好みの詳細レベルを選択してください：『詳細』は具体的なサブトピックを、『大まか』はより広いテーマを示します。",
    topics_viz_report_count_topics: "{count} 件のトピック",
    topics_viz_report_interactive_title: "レイヤー {layer} インタラクティブ可視化",
    topics_viz_report_static_title: "レイヤー {layer} 静的可視化",
    topics_viz_report_vis_title: "レイヤー {layer} の可視化",
    topics_viz_report_no_vis: "このジョブで使用できる可視化データはまだありません。",
    topics_viz_report_vis_wait: "可視化データの生成には数分かかる場合があります。",
    topics_viz_report_no_jobs: "可視化ジョブが見つかりません。",

    // Headers & Overview placeholders
    majority_opinion: "主要な意見",
    uncertainty: "不確実な項目",
    all_comments: "すべての意見",
    participant_groups: "参加者グループ",
}

export default s
